### ISSUE TITLE
Where can i find the data/gtea/label.json or data/gtea/mapping.txt file?

### ISSUE THREAD

**Issue by SatMa34** [Thinksky5124/SVTAS#10]
I tried to process the gtea data following the instruction using this script:
python tools/transform_segmentation_label.py data/gtea data/gtea/groundTruth data/gtea --mode localization --fps 15

where can i find the mapping.txt file that should be in the path of gtea?

**Comment by Thinksky5124** [comment]
You can get mapping.txt by downloading feature file from [ms-tcn](https://github.com/yabufarha/ms-tcn).

**Comment by SatMa34** [comment]
> You can get mapping.txt by downloading feature file from [ms-tcn](https://github.com/yabufarha/ms-tcn).

but it seems only mapping.txt of 50salads is included in this file?

**Comment by SatMa34** [comment]
> You can get mapping.txt by downloading feature file from [ms-tcn](https://github.com/yabufarha/ms-tcn).

sorry about that, i found that mapping file
