### ISSUE TITLE
Configs for Transeger

### ISSUE THREAD

**Issue by jazzseow** [Thinksky5124/SVTAS#4]
Hi, thank you for your work.

I am trying to reproduce the paper's results. May i know which is the Transeger configs you've used?

**Comment by Thinksky5124** [comment]
We are deeply sorry about this repo are under development, so the main branch will have bugs. However, you can checkout branch to svtas-paper to get transeger model config: [svtas-paper](https://github.com/Thinksky5124/SVTAS/tree/svtas-paper)

**Comment by jazzseow** [comment]
I see, thank you very much
