### ISSUE TITLE
关于使用asformer在k=32的情况下在GTEA数据集的表现

### ISSUE THREAD

**Issue by Yuuuumie** [Thinksky5124/SVTAS#8]
请问你们asformer在k=32的片段长度下的性能，是使用全视频训练32帧片段测试，还是32帧片段训练32帧片段测试，或是其他的什么训练策略呢？以及是将asformer的block num降低到了多少呢？感谢您的回答

**Comment by Thinksky5124** [comment]
32帧片段训练32帧片段测试，没有降低block num
