### ISSUE TITLE
关于Transeger中的文本初始化

### ISSUE THREAD

**Issue by Yuuuumie** [Thinksky5124/SVTAS#9]
Traceback (most recent call last):
  File "main.py", line 121, in <module>
    main()
  File "main.py", line 111, in main
    train(cfg,
  File "/home/pengfang/SVTAS-svtas-paper/tasks/train.py", line 202, in train
    runner.run_one_iter(data=data, r_tic=r_tic, epoch=epoch)
  File "/home/pengfang/SVTAS-svtas-paper/tasks/runner.py", line 259, in run_one_iter
    self.run_one_clip(sliding_seg)
  File "/home/pengfang/SVTAS-svtas-paper/tasks/runner.py", line 228, in run_one_clip
    score, loss_dict = self._model_forward(data_dict)
  File "/home/pengfang/SVTAS-svtas-paper/tasks/runner.py", line 200, in _model_forward
    outputs = self.model(input_data)
  File "/home/pengfang/.conda/envs/svtas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pengfang/SVTAS-svtas-paper/model/architectures/segmentation/transeger.py", line 77, in forward
    text_output = self.text_backbone(text_input)
  File "/home/pengfang/.conda/envs/svtas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pengfang/SVTAS-svtas-paper/model/architectures/general/encoder_2_decoder.py", line 64, in forward
    x = self.encoder(x, masks)
  File "/home/pengfang/.conda/envs/svtas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pengfang/SVTAS-svtas-paper/model/backbones/language/learner_prompt.py", line 87, in forward
    print('labels',labels.size())
AttributeError: 'NoneType' object has no attribute 'size'

在运行尝试运行transeger时，发现text_backbone的输入无法初始化，因为是第一个片段，所以class Transger中的self.last_clip_labels为None，无法进行文本编码，请问是代码的bug还是我的输入需要调整？

**Comment by Thinksky5124** [comment]
Sorry, the my original repo did not contain this line of code, please check if you added it yourself
my original repo in Line 86-92:
```python
def forward(self, labels, masks):
    b, temporal_len = masks.shape
    prompts, pad_masks = self.prompt_learner(labels, b, temporal_len, masks.device)
    # [N T U D]
    prompts = prompts.to(masks.device)
    # [N T U 1] -> [N*T U 1]
    pad_masks = pad_masks.reshape([-1] + list(pad_masks.shape[2:])).to(masks. Device)
```

**Comment by Yuuuumie** [comment]
yes，’print('labels',labels.size())‘ is added by myself in order to check the input of the LearnerPromptTextEncoder, and then I find it is None. Could you teach me how to initialize the input of the text encoder?

**Comment by Yuuuumie** [comment]
> 

yes，’print('labels',labels.size())‘ is added by myself in order to check the input of the LearnerPromptTextEncoder, and then I find it is None. Could you teach me how to initialize the input of the text encoder?

**Comment by Yuuuumie** [comment]
yes，’print('labels',labels.size())‘ is added by myself in order to check the input of the LearnerPromptTextEncoder, and then I find it is None. Could you teach me how to initialize the input of the text encoder? @Thinksky5124

**Comment by Thinksky5124** [comment]
repo `https://github.com/Thinksky5124/SVTAS/blob/svtas-paper/model/backbones/language/learner_prompt.py` Line 253-257:
```python
def forward(self, last_clip_labels, batch_size, temporal_len, device):
    #! this judge
    if last_clip_labels is None:
        start_promot = self._tokenizer.tokenize("").to(device)
        start_promot_embedding = self.token_embedding(start_promot)
        prompts = start_promot_embedding[:, :1].expand(batch_size, temporal_len // self.sample_rate, self.max_len, -1)
    else:
        text_list = []
        for b in range(batch_size):
            if torch.any(last_clip_labels[b,:] == self.ignore_index):
                end_promot = self._tokenizer.tokenize("").to(device)
                end_promot_embedding = self.token_embedding(end_promot)
                embedding = end_promot_embedding[:, 1:2].expand(1, temporal_len // self.sample_rate, self.max_len, -1)
                text_list.append(embedding)
            else:
                embedding = self.convert_id_to_promot(last_clip_labels[b, ::self.sample_rate])
                text_list.append(embedding.unsqueeze(0))
        
        # [N T U D]
        prompts = torch.cat(text_list, dim=0)
    pad_masks = torch.where(prompts != 0., torch.ones_like(prompts), torch.zeros_like(prompts))[:, :, :, 0:1]
    return prompts, pad_masks
```
deal with the problem of `label` is None, so, I think this is your problem

**Comment by Yuuuumie** [comment]
yeah ,I find my datasets' groundtruth was wrong. Thank you!
